<head><title></title></head>
<body>

<?php
include 'open.php';

//Override the PHP configuration file to display all errors
//This is useful during development but generally disabled before release
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

//Collect the posted value in a variable called $item

echo "<h2>Happiness Score and Danceability in each Country</h2>";
//Determine if any input was actually collected
if ($stmt = $conn->prepare(
    "WITH
    Top10SongPerCountry AS (SELECT country, YEAR(startDate) as year, songID 
                        FROM SpotifyChart 
                        WHERE pos <= 25),
    TopSongDance AS (SELECT danceability, year, country, songName, Song.songID
                    FROM Top10SongPerCountry JOIN Song ON Top10SongPerCountry.songID = Song.songID), 
    AvgDancePerCountry AS (SELECT  country, year, ROUND(avg(danceability), 2) as AverageDanceability
                        FROM TopSongDance
                        GROUP BY country, year)
    SELECT CH.country, CH.year, happinessScore, AverageDanceability
    FROM CountryHappiness as CH JOIN AvgDancePerCountry as DC 
    ON CH.country = DC.country and CH.year = DC.year; ")) {
       //Attach the ? in prepared statements to variables (even if those variables
       //don't hold the values we want yet).  First parameter is a list of types of
       //the variables that follow: 's' means string, 'i' means integer, 'd' means
       //double. E.g., for a statment with 3 ?'s, where middle parameter is an integer
       //and the other two are strings, the first argument included should be "sis".

       //Run the actual query
       if ($stmt->execute()) {

        //Store result set generated by the prepared statement
        $result = $stmt->get_result();

        if (($result) && ($result->num_rows != 0)) {

           //Create table to display results
           echo "<table border=\"1px solid black\">";
           echo "<tr><th> Country </th> <th> Year </th> <th> Happiness Score </th> <th> Danceability </th></tr>";
             foreach($result as $row){

             // reset the attribute names array
             $flist = $result->fetch_fields();
                 echo "<tr>";
                 foreach($flist as $fname){
                     echo "<td>".$row[$fname->name]."</td>";
             }
                 echo "</tr>";
             }

           echo "</table>";

        }      else {
        //if ($result->num_rows == 0) {
           //Result contains no rows at all
           echo "Insufficient information to determine how danceability is affected by happiness score";

            }

        //We are done with the result set returned above, so free it
        $result->free_result();

     } else {

        //Call to execute failed, e.g. because server is no longer reachable,
        //or because supplied values are of the wrong type
        echo "Execute failed.<br>";
     }

     //Close down the prepared statement
     $stmt->close();

  } else {

      //A problem occurred when preparing the statement; check for syntax errors
      //and misspelled attribute names in the statement string.
     echo "Prepare failed.<br>";
     $error = $conn->errno . ' ' . $conn->error;
     echo $error;
  }



//Close the connection created in open.php
$conn->close();
?>
</body>
