<head><title></title></head>
<body>

<?php
include 'open.php';

//Override the PHP configuration file to display all errors
//This is useful during development but generally disabled before release
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

//Collect the posted value in a variable called $item

echo "<h2>Albums with more than one song in the top 10 of the charts</h2>";
//Determine if any input was actually collected
if ($stmt = $conn->prepare(
    "WITH 
Top10Song AS (SELECT DISTINCT songID AS sid 
                FROM SpotifyChart
                WHERE pos <= 10), 
Top10SongAlbums AS (SELECT * 
                FROM AlbumTracks JOIN Top10Song ON AlbumTracks.songID = Top10Song.sid),
AlbumSongCount AS (SELECT *, count(*) AS NumTop10Songs
                FROM Top10SongAlbums
                GROUP BY albumID),
UniqueAlbums AS (SELECT DISTINCT albumID 
    FROM AlbumSongCount
    WHERE NumTop10Songs > 1)
SELECT albumName 
    FROM UniqueAlbums JOIN Album ON UniqueAlbums.albumID = Album.albumID;")) {
       //Attach the ? in prepared statements to variables (even if those variables
       //don't hold the values we want yet).  First parameter is a list of types of
       //the variables that follow: 's' means string, 'i' means integer, 'd' means
       //double. E.g., for a statment with 3 ?'s, where middle parameter is an integer
       //and the other two are strings, the first argument included should be "sis".

       //Run the actual query
       if ($stmt->execute()) {

        //Store result set generated by the prepared statement
        $result = $stmt->get_result();

        if (($result) && ($result->num_rows != 0)) {

           //Create table to display results
           echo "<table border=\"1px solid black\">";
           echo "<tr><th> Album Name</th></tr>";
             foreach($result as $row){

             // reset the attribute names array
             $flist = $result->fetch_fields();
                 echo "<tr>";
                 foreach($flist as $fname){
                     echo "<td>".$row[$fname->name]."</td>";
             }
                 echo "</tr>";
             }

           echo "</table>";

        }      else {
        //if ($result->num_rows == 0) {
           //Result contains no rows at all
           echo "No albums found with more than one top 10 song";

            }

        //We are done with the result set returned above, so free it
        $result->free_result();

     } else {

        //Call to execute failed, e.g. because server is no longer reachable,
        //or because supplied values are of the wrong type
        echo "Execute failed.<br>";
     }

     //Close down the prepared statement
     $stmt->close();

  } else {

      //A problem occurred when preparing the statement; check for syntax errors
      //and misspelled attribute names in the statement string.
     echo "Prepare failed.<br>";
     $error = $conn->errno . ' ' . $conn->error;
     echo $error;
  }



//Close the connection created in open.php
$conn->close();
?>
</body>
