<head><title></title></head>
<body>

<?php
include 'open.php';

//Override the PHP configuration file to display all errors
//This is useful during development but generally disabled before release
ini_set('error_reporting', E_ALL);
ini_set('display_errors', true);

echo "<h2>Percent of top charting songs that are explicit</h2>";


//Prepare a statement that we can later execute. The ?'s are placeholders for
//parameters whose values we will set before we run the query.
if ($stmt = $conn->prepare(
   "WITH 
   TopSongs AS (SELECT DISTINCT songID as songID
               FROM SpotifyChart),
   
   SongCount AS (SELECT count(songID) as num_songs
               FROM TopSongs), 
   
   ExpCount AS (SELECT sum(explicit) as exp_count
               FROM TopSongs JOIN Song ON TopSongs.songID = Song.songID)
   
   SELECT ROUND(100 * exp_count / num_songs,2) AS PercentExplicit
           FROM SongCount JOIN ExpCount;")) {

   //Run the actual query
   if ($stmt->execute()) {

      //Store result set generated by the prepared statement
      $result = $stmt->get_result();

      if (($result) && ($result->num_rows != 0)) {
   
         //Create table to display results
         echo "<table border=\"1px solid black\">";
         echo "<tr><th> State </th> <th> Percent of Explicit Songs </th></tr>";

         //Report result set by visiting each row in it
         while ($row = $result->fetch_row()) {
            echo "<tr>";
            // echo "<td>".$row[0]."</td>";
            echo "<td>".$row[1]."</td>";
            // echo "<td>".$row[2]."</td>";
            echo "</tr>";
         } 
      
   
         echo "</table>";
         
      }	else {
      //if ($result->num_rows == 0) {
         //Result contains no rows at all
         echo "No explicit songs found";

      }

      //We are done with the result set returned above, so free it
      $result->free_result();
   
   } else {

      //Call to execute failed, e.g. because server is no longer reachable,
   //or because supplied values are of the wrong type
      echo "Execute failed.<br>";
   }

   //Close down the prepared statement
   $stmt->close();

} else {

      //A problem occurred when preparing the statement; check for syntax errors
      //and misspelled attribute names in the statement string.
   echo "Prepare failed.<br>";
   $error = $conn->errno . ' ' . $conn->error;
   echo $error; 
}

//Close the connection created in open.php
$conn->close();
?>
</body>